### ISSUE TITLE
Survey for Knowledge Graphs Meet Multi-Modal Learning

### ISSUE THREAD

**Issue by hackerchenzhuo** [heathersherry/Knowledge-Graph-Tutorials-and-Papers#6]
Hi, we have preprinted our Survey recently: **[Knowledge Graphs Meet Multi-Modal Learning: A Comprehensive Survey](http://arxiv.org/abs/2402.05391)  [[`Repo`](https://github.com/zjukg/KG-MM-Survey)].**

Would you mind involving it in your Repo?

Thank you so much!

**Comment by heathersherry** [comment]
> Hi, we have preprinted our Survey recently: **[Knowledge Graphs Meet Multi-Modal Learning: A Comprehensive Survey](http://arxiv.org/abs/2402.05391) [[`Repo`](https://github.com/zjukg/KG-MM-Survey)].**
> 
> Would you mind involving it in your Repo?
> 
> Thank you so much!

Sure! I have already added it in the [MMKG session](https://github.com/heathersherry/Knowledge-Graph-Tutorials-and-Papers/blob/master/topics/MMKG.md).
Any info/PR is welcomed in this repo. Thanks a lot for your info and contriubtion! :)
